version: '3.7'


networks:
    backend:
        driver: bridge
services:
  imger-api:
    build: .
    ports:
      - "4005:4005"
    environment:
      - REDIS_URL=redis://redis-db:6379/0
      - MONGO_URL=mongodb://mongo-db:27017
    command: ["gin", "-d", "/go/src/github.com/RexterR/imger/cmd/imgerapi/", "-p", "4005", "-i"]
    volumes:
      - .:/go/src/github.com/RexterR/imger
    networks:
            - backend
    depends_on:
      - redis-db
      - mongo-db

  redis-db:
    image: redis:4-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/config/redis.conf
    command: redis-server /config/redis.conf
    restart: always
    networks:
            - backend

  mongo-db:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    networks:
            - backend