version: '3.7'

services:
  redis-db:
    image: redis:4-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/config/redis.conf
    command: redis-server /config/redis.conf
    restart: always

  mongo-db:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always